#!/bin/sh
#
# Start mdev....
#
TAG="MDEV"
case "$1" in
  start)
	logger -t ${TAG} -s "Starting mdev..."
	echo > /dev/mdev.seq
	echo /sbin/mdev >/proc/sys/kernel/hotplug
	/sbin/mdev -s
	# coldplug modules
	find /sys/ -name modalias -print0 | xargs -0 sort -u -z | xargs -0 modprobe -abq
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
