#!/bin/sh
#
# Start mount....
#

case "$1" in
  start)
	printf "Starting mount SD card..."
	/bin/mount -t vfat -o uid=1000,gid=1000 /dev/mmcblk0p1 /media/sd
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	printf "Starting mount mtd0..."
	/bin/mount -t jffs2 /dev/mtdblock0 /system
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	printf "Starting mount mtd1..."
	/bin/mount -t jffs2 /dev/mtdblock1 /userdata 
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  stop)
	/bin/umount /media/sd
	/bin/umount /system
	/bin/umount /userdata
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
