#!/bin/sh
#
# Start mount....
#

TAG="MOUNT"

do_mount_SD()
{
	mount -t vfat -o uid=1000,gid=1000 /dev/mmcblk0p1 /media/sd
	return $?
}

do_make_dir()
{
	if [ ! -e /media/sd/ftp ]; then
		logger -t ${TAG} -s "SD card is empty,we need to create the directory."
		mkdir -pv /media/sd/ftp/upgrade &&
        mkdir -pv /media/sd/ftp/PIC &&
        mkdir -pv /media/sd/ftp/Measurement &&
        mkdir -pv /media/sd/ftp/logs &&
        mkdir -pv /media/sd/ftp/Config &&
        mkdir -pv /media/sd/ftp/Alarm &&
		return 0 || return 1
	else
		logger -t ${TAG} -s "SD card already contain the directory, just continue."
	fi
}

do_format_SD_and_mkdir()
{
	grep -q '/dev/mmcblk0p1 /media/sd' /proc/mounts && umount /media/sd
	mkfs.vfat /dev/mmcblk0p1 &&
	do_mount_SD &&
	do_make_dir &&
	return 0 || return 1
}

case "$1" in
  start)
	if [ -e /dev/mmcblk0p1 ]; then 
		logger -t ${TAG} -s "Starting mount SD card..."
		#/bin/mount -t vfat -o uid=1000,gid=1000 /dev/mmcblk0p1 /media/sd
		do_mount_SD && do_make_dir || do_format_SD_and_mkdir
		[ $? = 0 ] && logger -t ${TAG} -s "OK" || logger -t ${TAG} -s "FAIL"
	fi
	
	if [ -e /dev/mtdblock0 ]; then
		logger -t ${TAG} -s "Starting mount yy..."
		/bin/mount -t yaffs2 /dev/mtdblock0 /yy
		[ $? = 0 ] && logger -t ${TAG} -s "OK" || logger -t ${TAG} -s "FAIL"
	fi

	if [ -e /dev/mtdblock1 ];then
		logger -t ${TAG} -s "Starting mount userdata..."
		/bin/mount -t yaffs2 /dev/mtdblock1 /userdata 
		[ $? = 0 ] && logger -t ${TAG} -s "OK" || logger -t ${TAG} -s "FAIL"
	fi
	;;
  stop)
	/bin/umount /media/sd
	/bin/umount /yy
	/bin/umount /userdata
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
