#!/bin/sh
#
# Start logging
#

TAG="SYSLOG"
SYSLOGD_ARGS=-n
KLOGD_ARGS=-n
[ -r /etc/default/logging ] && . /etc/default/logging

start() {
	logger -t ${TAG} -s "Starting logging: "
	#LOGFILE="/userdata/log/syslog_$(date "+%Y%m%d_%H_%M_%S")"
	LOGFILE="/userdata/log/yytd_syslog"
	[ -d /userdata/log ] || mkdir /userdata/log
	[ -e $LOGFILE ] || touch $LOGFILE
	start-stop-daemon -b -S -q -m -p /var/run/syslogd.pid --exec /sbin/syslogd -- $SYSLOGD_ARGS -O $LOGFILE
	start-stop-daemon -b -S -q -m -p /var/run/klogd.pid --exec /sbin/klogd -- $KLOGD_ARGS
	logger -t ${TAG} -s "OK"
}

stop() {
	logger -t ${TAG} -s "Stopping logging: "
	start-stop-daemon -K -q -p /var/run/syslogd.pid
	start-stop-daemon -K -q -p /var/run/klogd.pid
	logger -t ${TAG} -s "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
