#!/bin/sh
#
# Start the network....
#

TAG="NETWORK"
# Debian ifupdown needs the /run/network lock directory
mkdir -p /run/network

case "$1" in
  start)
	logger -t ${TAG} -s "Starting network: "
	/sbin/ifup -a
	[ $? = 0 ] && logger -t ${TAG} -s "OK" || logger -t ${TAG} -s "FAIL"
	;;
  stop)
	logger -t ${TAG} -s "Stopping network: "
	/sbin/ifdown -a
	[ $? = 0 ] && logger -t ${TAG} -s "OK" || logger -t ${TAG} -s "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

