#!/bin/sh
#
# Start button demo....
#

case "$1" in
  start)
	echo "Starting button demo..."
	gpio_button_demo &
	echo "OK"
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
