#!/bin/sh
#
# Start button demo....
#

TAG="BUTTON"
case "$1" in
  start)
	logger -t ${TAG} -s "Starting button demo..."
	gpio_button_demo &
	logger -t ${TAG} -s "OK"
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
