#!/bin/sh
#
# Start button demo....
#

TAG="NTP"
case "$1" in
  start)
	logger -t ${TAG} -s "Starting ntpd service..."
	ntpd -n -N -q -p cn.ntp.org.cn &
	logger -t ${TAG} -s "OK"
	;;
  stop)
	;;
  restart|reload)
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
