#!/bin/sh

TAG="UPDATE"
#uboot="/media/sd/CASS/UPDATE/uboot.bin"
uImage="/media/sd/ftp/upgrade/uImage"
ZIP="/media/sd/ftp/upgrade/update.zip"
Current_system=""
MTD_PATH=""

do_check_signature()
{
	cd /media/sd/ftp/upgrade
	md5sum -s -c ${uImage}.md5sum &&
	logger -t ${TAG} -s "uImage md5sum is fine!" && return 0
	logger -t ${TAG} -s "uImage md5sum is invalid!"
	rm -rf ${uImage}*
	return 1
}

do_upgrade()
{
#	if [ -e ${uboot} ];then
#		logger -t ${TAG} -s "Starting upgrade uboot..."
#		flashcp ${uboot} /dev/mtd2
#		if [ $? = 0 ];then
#			logger -t ${TAG} -s "Upgrade uboot OK!" 
#			touch /media/sd/CASS/UPDATE/.uboot_upgrade_success
#		else
#			logger -t ${TAG} -s "Upgrade uboot FAIL!!!"
#			touch /media/sd/CASS/UPDATE/.uboot_upgrade_fail
#		fi 
#	fi
	
	if [ -e ${ZIP} ];then
		logger -t ${TAG} -s "Detecting update.zip, unzipping it..."
		unzip ${ZIP} -d /media/sd/ftp/upgrade
	else
		exit 1
	fi

	if [ -e ${uImage} ];then
		do_check_signature
		if [ $? = 0 ];then
			logger -t ${TAG} -s "Starting upgrade uImage..."
            fw_printenv > /var/run/env.txt
            Current_system=$(grep -o 'Current_system=.*' /var/run/env.txt | sed 's/Current_system=//')
            if [ ${Current_system} = "system_A" ];then
                logger -t ${TAG} -s "Current system is system_A, we will update the new image to system_B."
                MTD_PATH="/dev/mtd5"
            else
                logger -t ${TAG} -s "Current system is system_B, we will update the new image to system_A."
                MTD_PATH="/dev/mtd4"
            fi
            
            flash_erase ${MTD_PATH} 0x00 0x00 -q
			flashcp ${uImage} ${MTD_PATH}
			if [ $? = 0 ];then 
				logger -t ${TAG} -s "Upgrade uImage OK, Now we will reboot the system!" 
				touch /media/sd/ftp/upgrade/.uImage_upgrade_success_`date +%Y%m%d%H%M`
                if [ ${Current_system} = "system_A" ];then    
                    fw_setenv Current_system system_B
                else
                    fw_setenv Current_system system_A
                fi
				rm -rf ${uImage}* ${ZIP}
				reboot
			else
				logger -t ${TAG} -s "Upgrade uImage FAIL!!!"
				touch /media/sd/ftp/upgrade/.uImage_upgrade_fail_`date +%Y%m%d%H%M`
				rm -rf ${uImage}* ${ZIP}
			fi
		else
			rm -rf ${uImage}* ${ZIP}
            touch /media/sd/ftp/upgrade/.uImage_upgrade_fail_`date +%Y%m%d%H%M`
			exit 1
		fi
	else
		rm -rf ${uImage}* ${ZIP}
		exit 1
	fi
}

case "$1" in
	start)
		do_upgrade
		;;
	*)
		exit 1
		;;
esac
exit $?
