#!/bin/sh
#
# Start YYTD start.sh....
#


first_start(){
	if [ -e /dev/mtdblock5 ];then
		printf "Starting mount app mtdblock..."
		mount -t jffs2 /dev/mtdblock5 /tmp/ 
		if [ $? = 0 ];then 
			echo "OK" 
		else
			echo "FAIL" && exit 1
		fi
        fi
	
	printf "Uncompress app.tar.gz to yy folder"
	tar xf /tmp/app.tar.gz -C /yy/
	[ $? = 0 ] && echo "OK" || echo "FAIL" 
	
	umount /tmp/
	/yy/app/start.sh &
	
}

case "$1" in
  start)
        if [ -e /yy/app/start.sh ]; then
                printf "Starting YYTD app..."
                /yy/app/start.sh &
                [ $? = 0 ] && echo "OK" || echo "FAIL"
	else 
		first_start
		
        fi
        ;;
  stop)
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
