#!/bin/sh
#
# Start YYTD start.sh....
#

TAG="YYTD"
first_start(){
	if [ -e /dev/mtdblock5 ];then
		logger -t ${TAG} -s "Starting mount app mtdblock..."
		mount -t jffs2 /dev/mtdblock5 /tmp/ 
		if [ $? = 0 ];then 
			logger -t ${TAG} -s "OK" 
		else
			logger -t ${TAG} -s "FAIL" && exit 1
		fi
        fi
	
	logger -t ${TAG} -s "Uncompress app.tar.gz to yy folder"
	tar xf /tmp/app.tar.gz -C /yy/
	[ $? = 0 ] && logger -t ${TAG} -s "OK" || logger -t ${TAG} -s "FAIL" 
	
	umount /tmp/
	/yy/app/start.sh &
	
}

case "$1" in
  start)
        if [ -e /yy/app/start.sh ]; then
                logger -t ${TAG} -s "Starting YYTD app..."
                /yy/app/start.sh &
                [ $? = 0 ] && logger -t ${TAG} -s "OK" || logger -t ${TAG} -s "FAIL"
	else 
		first_start
		
        fi
        ;;
  stop)
        ;;
  restart|reload)
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
